project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu:
              - text: Hands-on Exercise 1A
                href: Hands-on_Ex/Hands-on_Ex1/Hands-on_Ex1.html
              - text: Hands-on Exercise 1B
                href: Hands-on_Ex/Hands-on_Ex1/Hands-on_Ex1B.html
              - text: Hands-on Exercise 2A
                href: Hands-on_Ex/Hands-on_Ex2/Hands-on_Ex2A.html
              - text: Hands-on Exercise 2B
                href: Hands-on_Ex/Hands-on_Ex2/Hands-on_Ex2B.html
              - text: Hands-on Exercise 2C
                href: Hands-on_Ex/Hands-on_Ex2/Hands-on_Ex2C.html
              - text: Hands-on Exercise 3
                href: Hands-on_Ex/Hands-on_Ex3/Hands-on_Ex3.html
      - text: In-class Exercises
        menu: 
              - text: In-class Exercise 1
                href: In-class_Ex/In-class_Ex1/In-class_Ex1.html
              - text: In-class Exercise 2 Spatial Weight
                href: In-class_Ex/In-class_Ex2/In-class_Ex2.html
              - text: In-class Exercise 2-EHSA
                href: In-class_Ex/In-class_Ex2/In-class_Ex2-EHSA.html
              - text: In-class Exercise 2-GLSA
                href: In-class_Ex/In-class_Ex2/In-class_Ex2-GLSA.html
              - text: In-class Exercise 3
                href: In-class_Ex/In-class_Ex3/In-class_Ex3.html
              - text: In-class Exercise 4-GDS
                href: In-class_Ex/In-class_Ex4/In-class_Ex4.html
              - text: In-class Exercise 4-SIMs
                href: In-class_Ex/In-class_Ex4/In-class_Ex4-SIMs.html
          
      - text: Take-home Exercises
        menu: 
          - text: Take-home Exercise 1
            href: Take-home_Ex/Take-home_Ex1/Take-home_Ex1.html
          - text: Take-home Exercise 2
            href: Take-home_Ex/Take-home_Ex2/Take-home_Ex2.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

